development:
  adapter: mysql2
  encoding: utf8
  database: suppert
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: suppert_test
  pool: 5
  username: root
  password: